# Generated by Django 5.1.2 on 2025-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_No', models.IntegerField(default=0)),
                ('Transaction_Date', models.DateField()),
                ('Value_Date', models.DateField()),
                ('Description', models.CharField(default='N/A', max_length=100)),
                ('Cheque_Number', models.CharField(default='N/A', max_length=50)),
                ('Debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
